package com.wdm.configuration.api.model;

public enum VersionEntities {
    AMERILINK,
    EMAIL,
    IBIDKLINK,
    VELOIDIBID,
    MOBILEADVERTISING,
    MPLATFORM,
    GRAPHIDKLINK,
    CENSUS,
    ZIPAMERILINK,
    ZIP4AMERILINK,
    SUMMARIZEDCREDIT,
    DONOTCALL,
    WIRELESS,
    DONOTMAIL,
    BANKRUPTCY,
    DECEASEDKNOWN,
    DECEASEDPROBABLE,
    PRISON,
    PUBLICHOUSING,
    NURSINGHOME,
    PHONEAPPENDWIRELESS,
    PHONEAPPENDLANDLINE;
}
